media:
  input: public/media
  output: media
content:
  - name: articles
    label: Articles
    path: articles
    type: collection
    view:
      fields: [ title, date ]
    fields:
      - { name: title, label: Title, type: string }
      - { name: date, label: Date, type: date }
      - {
          name: description,
          label: Description,
          type: string,
          options: { maxlength: 160 },
        }
      - { name: image, label: Image, type: image }
      - { name: body, label: Body, type: rich-text }
